### ISSUE TITLE
Whole site unreachable due TypeError: can't access property "replace", Ag[e] is undefined

### ISSUE THREAD

**Issue by KasperiP** [Testausserveri/testaustime-frontend#25]
Couldn't access my dashboard due TypeError. On happens on dashboard page when logged in. Image below should help. 

![image](https://user-images.githubusercontent.com/26027985/161754029-557727be-cf79-4fe2-9d64-5cd8c49bf253.png)

**Comment by Eldemarkki** [comment]
Opening until proven fixed
