### ISSUE TITLE
Selected projects shouldn't reset on page change

### ISSUE THREAD

**Issue by KasperiP** [Testausserveri/testaustime-frontend#28]
Currently selected projects reset on every page change. IMO this is bad UX and reset should only happen on page reload. Could be fixed by storing the state globally instead of on component level:

https://github.com/Testausserveri/testaustime-frontend/blob/91a43f655148c62acc2702a994bf0b16440ca088/src/components/Dashboard.tsx#L37

**Comment by Eldemarkki** [comment]
Fixed in 398f00afbbbbc71b8ebefe848f0a00c2c050055d
